#!/usr/bin/env bash
# parses Apache log files in list format.
#  Sepaeate visitors by IP and HTTP status code.
#  Show number of occurrences, IP, and HTTP status
#  code of each log, in sorted order.

myfile="apache-access.log"
awk -F' ' '{ print $1, $9}' $myfile | sort | uniq -c|sort -nr
