#!/usr/bin/env bash
# Loops from 1 to 10 and displays:
#   "bad luck" when loop reachs 4
#   "good luck" when loop reach 8
#   "Best School" iterate

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
